### ISSUE TITLE
Always got an error during ran production build

### ISSUE THREAD

**Issue by ujtordai** [zefoy/ngx-perfect-scrollbar#192]
## Hi all,

I always got an ERROR during ran production build, can see below, it's more interesting if I switched off the AoT build (with option -aot=false) the build successfully completed.

ERROR in : Error: Trying to import a source file from a node_modules package: import C:/pilot/playground/src/app/core/components/single-select/scrollbar-for-select.directive.ts from C:/pilot/playground
/node_modules/ng2-select/select/select.ngfactory.ts
    at TsCompilerAotCompilerTypeCheckHostAdapter.fileNameToModuleName (C:\pilot\playground\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:187:19)
    at AotCompiler._fileNameToModuleName (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:31099:24)
    at Object.importExpr$$1 [as importExpr] (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:31067:55)
    at singleProviderDef (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:20028:28)
    at providerDef (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:19962:9)
    at ViewBuilder._visitProviderOrDirective (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:28177:18)
    at ViewBuilder._visitDirective (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:28025:23)
    at C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:27926:32
    at Array.forEach (native)
    at ViewBuilder._visitElementOrTemplate (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:27916:23)
    at ViewBuilder.visitElement (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:27820:23)
    at ElementAst.visit (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:925:24)
    at visit (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:1366:37)
    at C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:1368:42
    at Array.forEach (native)
    at templateVisitAll (C:\pilot\playground\node_modules\@angular\compiler\bundles\compiler.umd.js:1367:10)_

Here is the file scrollbar-for-select.directive.ts

_import { PerfectScrollbarDirective, PerfectScrollbarConfig,
    PerfectScrollbarConfigInterface, PERFECT_SCROLLBAR_CONFIG } from 'ngx-perfect-scrollbar';
import { Directive, ElementRef, KeyValueDiffers, NgZone, Optional, Inject, PLATFORM_ID } from '@angular/core';
@Directive({
    selector: 'ul.ui-select-choices'
})
export class ScrollbarForSelectDirective extends PerfectScrollbarDirective {
    static psConfig = <PerfectScrollbarConfig>{
        suppressScrollX: true
    };
    constructor(private zn: NgZone, private diffs: KeyValueDiffers,
        public elementRef: ElementRef, @Inject(PLATFORM_ID) private platfId: Object,
        @Optional() @Inject(PERFECT_SCROLLBAR_CONFIG) private def: PerfectScrollbarConfigInterface) {
        super(zn, diffs, elementRef, platfId, ScrollbarForSelectDirective.psConfig);
    }
}_

Related packages & versions 

    Angular:   "^5.0.0",
    ng2-select :  "^2.0.0",
    ngx-bootstrap:  "~2.0.5",
    ngx-perfect-scrollbar:  "~5.3.5",

    Agular cli:  "^1.5.0",
    typescript:  "~2.4.2"_

Thank you in advance

Do you have anybody some idea how can I fix this problem?

I don't know is this post/issue related to this problem:

https://github.com/angular/angular-cli/issues/8308

**Comment by sconix** [comment]
I don't think this is related to this library and since there has not been any suggestions I will close this.
