### ISSUE TITLE
Help Wanted! Scroll detection.

### ISSUE THREAD

**Issue by gnasit** [zefoy/ngx-perfect-scrollbar#23]
I have two scrollbars and want to be able to move them together in the left/right scroll direction.
The way I thought i would try and do this is detect the scroll event and move the other scroll bar the same way that i detected the scroll event from, if there is a better way, then please advice.

Is there a way I can detect the scroll event?

I tried detecting the scroll event by creating a directive "track-scroll" which can track scroll events, but when i add that directive on the same div which also has the perfect-scrollbar directive, the perfect-scrollbar directive fails and i get the below error:

error_handler.js:54EXCEPTION: Error in ./GanttComponent class GanttComponent - inline template:15:33 caused by: Cannot read property 'offsetWidth' of undefined
ErrorHandler.handleError @ error_handler.js:54
(anonymous) @ application_ref.js:261
ZoneDelegate.invoke @ zone.js:242
onInvoke @ ng_zone.js:271
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:535
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:262
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:433
error_handler.js:56ORIGINAL EXCEPTION: Cannot read property 'offsetWidth' of undefined
ErrorHandler.handleError @ error_handler.js:56
(anonymous) @ application_ref.js:261
ZoneDelegate.invoke @ zone.js:242
onInvoke @ ng_zone.js:271
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:535
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:262
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:433
error_handler.js:59ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
(anonymous) @ application_ref.js:261
ZoneDelegate.invoke @ zone.js:242
onInvoke @ ng_zone.js:271
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:535
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:262
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:433
error_handler.js:60TypeError: Cannot read property 'offsetWidth' of undefined
    at PerfectScrollbarDirective.ngDoCheck (perfect-scrollbar.directive.js:16)
    at Wrapper_PerfectScrollbarDirective.ngDoCheck (/PerfectScrollbarModule/PerfectScrollbarDirective/wrapper.ngfactory.js:44)
    at CompiledTemplate.proxyViewClass.View_GanttComponent0.detectChangesInternal (/AppModule/GanttComponent/component.ngfactory.js:385)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (view.js:425)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (view.js:620)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (view.js:410)
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:61)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (view.js:425)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (view.js:620)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (view.js:410)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:29)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (view.js:425)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (view.js:620)
    at ViewRef_.detectChanges (view_ref.js:170)
    at application_ref.js:625
ErrorHandler.handleError @ error_handler.js:60
(anonymous) @ application_ref.js:261
ZoneDelegate.invoke @ zone.js:242
onInvoke @ ng_zone.js:271
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:535
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:262
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:433
error_handler.js:63ERROR CONTEXT:
ErrorHandler.handleError @ error_handler.js:63
(anonymous) @ application_ref.js:261
ZoneDelegate.invoke @ zone.js:242
onInvoke @ ng_zone.js:271
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:535
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:262
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:433
error_handler.js:64DebugContext {_view: C…e.proxyViewClass, _nodeIndex: 21, _tplRow: 15, _tplCol: 33}
ErrorHandler.handleError @ error_handler.js:64
(anonymous) @ application_ref.js:261
ZoneDelegate.invoke @ zone.js:242
onInvoke @ ng_zone.js:271
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:535
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:262
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:433
zone.js:420 Unhandled Promise rejection: Error in ./GanttComponent class GanttComponent - inline template:15:33 caused by: Cannot read property 'offsetWidth' of undefined ; Zone: <root> ; Task: Promise.then ; Value: ViewWrappedError {__zone_symbol__error: Error: Error in ./GanttComponent class GanttComponent - inline template:15:33 caused by: Cannot read…, _nativeError: ZoneAwareError, originalError: TypeError: Cannot read property 'offsetWidth' of undefined
    at PerfectScrollbarDirective.ngDoChec…, context: DebugContext, __zone_symbol__stack: "Error: Error in ./GanttComponent class GanttCompon…(http://localhost:4200/vendor.bundle.js:57165:20)"…} Error: Error in ./GanttComponent class GanttComponent - inline template:15:33 caused by: Cannot read property 'offsetWidth' of undefined
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7012:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:26468:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:26533:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:56238:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:77328:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:77301:18)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:77088:18)
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:61:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:77103:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:77298:44)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:77088:18)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:77103:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:77298:44)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:57165:20)
consoleError @ zone.js:420
_loop_1 @ zone.js:449
drainMicroTaskQueue @ zone.js:453
zone.js:422 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Error: Error in ./GanttComponent class GanttComponent - inline templat…, rejection: ViewWrappedError, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask}
consoleError @ zone.js:422
_loop_1 @ zone.js:449
drainMicroTaskQueue @ zone.js:453
error_handler.js:54 EXCEPTION: Cannot read property 'forEach' of undefined
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:331
onHandleError @ ng_zone.js:292
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
data.args.(anonymous function) @ zone.js:1376
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:331
onHandleError @ ng_zone.js:292
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
data.args.(anonymous function) @ zone.js:1376
error_handler.js:60 TypeError: Cannot read property 'forEach' of undefined
    at http://localhost:4200/main.bundle.js:4880:35
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6476:35)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:28119:37)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6475:40)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6352:47)
    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6546:33)
    at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:7577:25)
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:331
onHandleError @ ng_zone.js:292
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
data.args.(anonymous function) @ zone.js:1376
Subscriber.js:227 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at http://localhost:4200/main.bundle.js:4880:35
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6476:35)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:28119:37)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6475:40)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6352:47)
    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6546:33)
    at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:7577:25)
(anonymous) @ gantt.component.ts:51
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ ng_zone.js:262
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
ZoneTask.invoke @ zone.js:345
data.args.(anonymous function) @ zone.js:1376

**Comment by sconix** [comment]
I have just released 2.0.4 which should fix the directive causing the offsetWidth error.  Otherwise I think you are on the right track, i.e. can't think of any better way to do what you want to achieve.

**Comment by gnasit** [comment]
great. it works for me now, and I am also able to achieve the behavior that i wanted to have.! Thanks for the super quick turnaround, on the feature enhancement request as well..!!
